### ISSUE TITLE
Activation mode always in SNEAK on 1.15.2

### ISSUE THREAD

**Issue by martinambrus** [2008Choco/VeinMiner#37]
Also reported here: https://dev.bukkit.org/projects/vein-miner?comment=135
Just making an issue out of this, so it's more visible and recorded ;-)

**Activation Mode** for plugin version _VeinMiner-1.15.0_ doesn't work. It's always in **SNEAK MODE**, even after server restart, no errors in console.

**Comment by 2008Choco** [comment]
This has been resolved in commit [188bf0b](https://github.com/2008Choco/VeinMiner/commit/188bf0bdb41aa8cb969616498ecc858e7f7a3287) and will be available in a future version. For the time being, changing "ActivationMode" to "ActivationStrategy" in the configuration file will fix the issue :)

**Comment by HippHamster** [comment]
Seting ActivationStrategy in the config does not fix this for me.

**Comment by 2008Choco** [comment]
This has been resolved in the most recent release, VeinMiner 1.15.1. However, this change only affects the default configuration file! If you notice `ActivationMode` in your config file, please change it instead to `ActivationStrategy` and this issue will be resolved.
